# Generated by Django 4.2 on 2025-07-13 15:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
